import {BLACK_HOLES} from './black-hole-data.js';
import { LIBRARY_ENTRIES, LIBRARY_CATEGORIES } from './catalog.js';
import { CELESTIAL_BODIES, SURFACE_SITES, LOCAL_ORBITERS, FALLBACK_SPACECRAFT, LAGRANGE_OBJECTS } from './solar-data.js';
import { COSMIC_OBJECTS, LY_KM } from './cosmic-data.js';
export const ENCYCLOPEDIA_CATEGORIES=[{id:'all',label:'Todo el atlas'},{id:'solar',label:'Sistema solar'},{id:'stars',label:'Estrellas'},{id:'galaxies',label:'Galaxias'},{id:'cosmology',label:'Universo y cosmología'},{id:'methods',label:'Guías del atlas'},{id:'history',label:'Historia espacial'},{id:'deep-space',label:'Sondas y observatorios'},{id:'surface',label:'Lugares de superficie'},...LIBRARY_CATEGORIES.filter(x=>!['all','deep-space'].includes(x.id)).map(x=>({...x,label:x.id==='constellation'?'Constelaciones satelitales':x.label}))];
const bodyNotes={
 sun:'Estrella de secuencia principal de tipo G2V. La fusión de hidrógeno en el núcleo suministra la energía que ilumina el sistema solar. La fotosfera no es una superficie sólida; las imágenes ultravioletas usadas como textura muestran plasma y se representan en falso color.',
 mercury:'El planeta más próximo al Sol tiene una superficie rocosa craterizada y una exosfera muy tenue. Su rotación está en resonancia 3:2 con su órbita: completa tres giros por cada dos revoluciones alrededor del Sol.',
 venus:'Planeta rocoso cubierto por una atmósfera muy densa de dióxido de carbono y nubes de ácido sulfúrico. Su superficie caliente solo es visible mediante radar o desde sondas que atravesaron las nubes. El exterior del visor representa una cubierta nubosa uniforme; no el relieve radar oculto bajo ella.',
 earth:'Océanos, continentes y atmósfera hacen de la Tierra el único mundo con vida conocida. La capa Color natural usa un mapa global NASA en color natural; no es una imagen meteorológica en directo. La esfera oculta físicamente los objetos situados detrás. Las luces urbanas aparecen en el hemisferio nocturno.',
 moon:'Satélite natural de la Tierra con rotación síncrona. Conserva mares basálticos, tierras altas y cráteres. El mapa LROC y el relieve LOLA proceden de Lunar Reconnaissance Orbiter. Los emplazamientos históricos permanecen sobre la superficie; la órbita lunar del visor es aproximada.',
 mars:'Mundo rocoso con una atmósfera tenue de dióxido de carbono. El color rojizo procede de minerales de hierro oxidados. Sus valles, volcanes y depósitos sedimentarios conservan información sobre antiguos ambientes con agua.',
 phobos:'Luna interior irregular de Marte. Orbita más rápido de lo que rota el planeta. La esfera usa un radio equivalente para indicar escala, no reproduce su forma irregular exacta.',
 deimos:'Pequeño satélite exterior de Marte, de forma irregular y superficie cubierta por regolito. Se muestra su radio equivalente, sin inventar un mapa de superficie de alta resolución.',
 jupiter:'Gigante gaseoso con bandas nubosas, tormentas y una magnetosfera intensa. No tiene una superficie sólida definida como la terrestre. El radio de referencia describe una capa de presión de su atmósfera.',
 io:'Luna de Júpiter sometida a intenso calentamiento por mareas. Es el mundo volcánicamente más activo del sistema solar. Su superficie cambia con la actividad de numerosos volcanes.',
 europa:'Luna helada de Júpiter. Las fracturas del hielo y la evidencia geofísica apuntan a un océano líquido interior, mantenido por calentamiento de mareas.',
 ganymede:'La mayor luna del sistema solar, de tamaño superior a Mercurio. Posee un campo magnético propio y una superficie que alterna regiones antiguas oscuras y terrenos surcados.',
 callisto:'Luna exterior galileana de Júpiter. Su superficie está muy craterizada y conserva una larga historia de impactos. Es menos afectada por la radiación joviana que las lunas interiores.',
 saturn:'Gigante gaseoso rodeado por anillos compuestos principalmente por hielo. Los anillos tienen radios físicos y huecos diferenciados; la división de Cassini separa los anillos A y B.',
 enceladus:'Pequeña luna helada de Saturno. Cassini detectó chorros de vapor, hielo y compuestos orgánicos que emergen cerca del polo sur y se relacionan con un océano interior.',
 titan:'La mayor luna de Saturno posee una atmósfera densa de nitrógeno. En su superficie hay lagos y mares de metano y etano. Huygens descendió a su superficie en 2005.',
 uranus:'Gigante de hielo cuya inclinación axial extrema cambia profundamente sus estaciones. Su color azul verdoso está relacionado con el metano y la estructura de sus nubes y brumas.',
 neptune:'Gigante de hielo exterior, con vientos intensos y una atmósfera de hidrógeno, helio y metano. Los mapas de distintas misiones pueden realzar colores que no equivalen a la visión humana.',
 triton:'La gran luna de Neptuno tiene una órbita retrógrada y se considera un probable objeto capturado del cinturón de Kuiper. Voyager 2 observó actividad de géiseres en su superficie.',
};
const methods=[
 ['cosmic-strings','Cuerdas cósmicas','Hipótesis física, sin ubicaciones observadas','Las cuerdas cósmicas serían defectos unidimensionales que algunos modelos del universo temprano permiten tras transiciones de fase. No son las cuerdas de la teoría de supercuerdas en general, ni filamentos de galaxias. Podrían producir lentes gravitacionales dobles, ondas gravitacionales o discontinuidades en el fondo de microondas. No constituyen una envoltura situada junto al CMB: sus posibles señales se buscarían en distintas épocas y distancias. No existe un catálogo confirmado para colocarlas en Universal. Por eso esta ficha explica la hipótesis sin asignarle posiciones ni dibujar una red como si se hubiera observado.',['Estado','Hipótesis; no detección confirmada'],['Señales propuestas','Lentes, ondas gravitacionales y discontinuidades del CMB'],['Referencia','Planck 2013 results XXV: límites observacionales, no detección']],

 ['atlas-guide','Del mundo cercano a la primera luz','Guía de Universal','Universal une la Tierra, las órbitas artificiales, el sistema solar, las estrellas y las grandes escalas cósmicas. Puedes viajar con la rueda, seleccionar un objeto y consultar su ficha, o explorar libremente la galaxia. Los tamaños de los cuerpos y sus distancias comparten una escala física. Los puntos luminosos, las etiquetas y los colores de densidad son ayudas de lectura. La enciclopedia distingue catálogos, fotografías, cálculos y modelos: una imagen bella no convierte una reconstrucción en una medición.',['Explorar','Rueda, arrastre y selección'],['Consultar','Capítulos, búsqueda, imágenes, datos y fuentes']],
 ['last-scattering','La superficie de última dispersión','Dónde situar el fondo cósmico de microondas','Unos 380.000 años después del Big Bang, el enfriamiento permitió que los electrones y protones formaran átomos y que la luz viajara con mucha menos dispersión. Esa radiación se observa hoy como microondas, a unos 2,725 K. Vemos una superficie de última dispersión centrada en nuestro punto de observación, a una distancia comóvil actual aproximada de 45.500 millones de años luz. Está dentro del horizonte observable, cuyo radio es de unos 46.500 millones. No es una pared material ni un borde del universo. El mapa Planck 2018/SMICA muestra diferencias de temperatura en falso color (±300 μK); WMAP de cinco años sigue disponible para comparar. El mapa no contiene galaxias o filamentos actuales. La esfera externa es una visualización pedagógica de un mapa angular observado.',['Edad al emitirse','Aproximadamente 380.000 años'],['Temperatura media actual','Aproximadamente 2,725 K'],['Rango de Planck','−300 a +300 μK'],['Distancia comóvil adoptada','45.500 millones de años luz; depende del modelo cosmológico']],

 ['earth-detail','Tierra: imágenes y nubes','Mosaicos y observaciones diarias','El detalle terrestre se descarga por teselas de Esri World Imagery al acercarse, con resolución y fechas variables. Se pueden distinguir calles donde exista cobertura; no son edificios 3D, Street View ni imágenes en directo. La capa NASA GIBS muestra superficie y nubes de MODIS del día anterior, con posibles huecos y retrasos, no una capa meteorológica aislada. No sigue el reloj histórico. Cerca del suelo el zoom depende de la altura y la cámara acompaña la rotación terrestre.',['Detalle','Esri · hasta nivel 19 según cobertura'],['Observación diaria','NASA GIBS / MODIS · unos 250–300 m']],
 ['galactic-flight','Explorar la Vía Láctea','Traslación libre y sectores estelares','Con el foco en el visor, W/A/S/D permiten trasladarse sobre el plano horizontal desde cualquier escala y E/C subir o bajar sobre el eje Y; Q/Z giran a izquierda/derecha. Shift acelera; el botón derecho desplaza el foco. La rueda cambia gradualmente la distancia de exploración. Los sectores de 120 años luz se generan de forma reproducible alrededor de la cámara: su población ilustra el gradiente de densidad del disco y cada punto se identifica como estrella modelada. No son descubrimientos ni un catálogo de toda la galaxia. Las estrellas HYG siguen siendo observaciones separadas.',['Navegación','Espacio físico y origen móvil'],['Población','Modelo determinista, no catálogo observado']],
 ['photographic-sky','Fotografías del cielo y Andrómeda','ESO / Digitized Sky Survey 2','El cielo próximo al Sol utiliza el panorama eso0932a de ESO/S. Brunier, con proyección celeste aproximada. Es una fotografía de larga exposición y no la apariencia a simple vista. Se desvanece al viajar lejos del Sol, pues esa perspectiva deja de ser válida. M31 utiliza heic1502b: NASA, ESA, Digitized Sky Survey 2, agradecimiento a Davide De Martin. Su plano fotográfico se atenúa al entrar en la galaxia o verla desde otro ángulo, dando paso al modelo 3D. Ambas imágenes se atribuyen en pantalla y están bajo CC BY 4.0.',['Cielo','ESO/S. Brunier · 6000 × 3000'],['M31','NASA, ESA, DSS2 · Davide De Martin']],

 ['physical-scale','Una escala física común','Distancias, radios y ayudas de lectura','El visor conserva los cocientes entre radios y distancias en kilómetros. Al alejarse cambia la unidad interna de dibujo, nunca las proporciones. A escala del sistema solar, una Tierra de tamaño correcto es casi invisible: por eso existen marcadores desactivables. El tamaño de esos puntos, las etiquetas, el grosor de las órbitas y los destellos son ayudas de lectura, no tamaños físicos.',['Distancia local','Kilómetros / unidades astronómicas'],['Distancia estelar','Años luz / pársecs']],
 ['hyg-catalog','Catálogo estelar HYG','Hipparcos, Yale y Gliese','El catálogo combina nombres, posiciones, distancias, magnitudes y tipos espectrales. Se excluyen registros sin distancia utilizable (valor centinela de 100.000 pc). Las coordenadas son de época J2000 y las distancias tienen incertidumbre. No incluye todas las estrellas de la Vía Láctea y no es Gaia completo. Puedes buscar por nombre o identificador HIP/HYG y navegar a cada estrella incluida.',['Época','J2000'],['Licencia','CC BY-SA 4.0 · David Nash']],
 ['galaxy-surveys','Galaxias observadas: 2MRS y SDSS','474.643 registros de sondeos, con posibles coincidencias entre catálogos','2MRS aporta 43.380 galaxias con cz mayor de 600 km/s. Sus distancias se calculan en un modelo cosmológico plano con H₀ = 73 km/s/Mpc, Ωm = 0,3 y ΩΛ = 0,7; las velocidades peculiares introducen errores, sobre todo cerca. SDSS aporta los 431.263 registros binarios servidos por WorldWide Telescope, preservando sus distancias con h = 0,73 y su huella angular. Los conos de cobertura y zonas no observadas no son bordes del universo ni necesariamente vacíos. No se suman los dos catálogos como si fueran galaxias únicas: pueden contener el mismo objeto. Sus perfiles luminosos son localizadores, no fotografías ni diámetros medidos. Carga los catálogos desde Capas o al alejarte; luego busca por NGC, 2MASX o identificador SDSS completo.',['2MRS','Huchra et al. 2012 / CDS'],['SDSS','Catálogo 3D de WorldWide Telescope']],
 ['cosmic-flows','Laniakea: velocidades y cuencas','Reconstrucción Cosmicflows-4 publicada','Las curvas muestran líneas de corriente de un campo de velocidades peculiares reconstruido. El color dorado identifica semillas situadas dentro de la cuenca de Laniakea; el azul, semillas fuera. La envolvente procede de la segmentación publicada en 2023, no de una esfera inventada. Se utiliza el campo no agrupado CF4 de 64³ celdas y la cuenca de 128³ celdas, ambos de 1000 Mpc/h por lado, con h = 0,75. Las curvas no son trayectorias futuras o pasadas de galaxias. La interpolación no añade resolución a las mediciones. Las soluciones agrupadas y no agrupadas difieren: Laniakea no es una frontera material exacta ni una estructura aislada.',['Velocidades','Courtois et al., 2023'],['Cuencas','Dupuy y Courtois, 2023']],
 ['cosmic-web','La red cósmica','Densidad, filamentos, paredes y vacíos','La imagen violeta y dorada representa densidad en falso color, no luz visible de galaxias. Fuera del volumen cartografiado, Universal usa una realización pedagógica de la aproximación de Zel’dovich: un campo gaussiano desplaza materia y genera concentraciones anisótropas, paredes y vacíos. No utiliza enlaces rectos entre puntos aleatorios. El espectro es ilustrativo, no un ajuste cosmológico ni los datos de Millennium. Se integra la densidad a través de campos tridimensionales de 192³ y 256³ celdas, con límites difusos. El campo exterior es una realización estadística gruesa independiente: su textura ilustra concentraciones, no filamentos individuales medidos a esa escala. Las transiciones entre campos son visuales, no regiones observadas enlazadas físicamente. Este modelo no incluye evolución de N cuerpos, gas ni un cono de luz cosmológico.',['Modelo','Zel’dovich pedagógico + población estadística exterior'],['Colores','Densidad representada, no fotografía']],
 ['observable-distance','13.800 frente a 46.500 millones','Edad y distancia no son lo mismo','La edad del universo y el radio actual del universo observable son magnitudes diferentes. Mientras la luz viajaba, el espacio se expandía. Por eso el radio comóvil actual puede rondar 46.500 millones de años luz. La vista externa sirve para entender el volumen; ningún observador puede situarse fuera y fotografiarlo así. Tampoco vemos simultáneamente todos los objetos tal como son hoy.',['Edad aproximada','13.800 millones de años'],['Radio comóvil aproximado','46.500 millones de años luz']],
 ['orbital-data','Órbitas y basura espacial','Qué significa el catálogo público','Los elementos OMM describen órbitas medias y se propagan con SGP4. La precisión se degrada con la distancia a su época; el visor oculta los elementos actuales fuera de su ventana temporal. Los fragmentos mostrados pertenecen a catálogos públicos seleccionados. No es toda la basura espacial: existen objetos demasiado pequeños para rastrearlos y datos no publicados.',['Modelo','SGP4 / OMM'],['Uso','Exploración educativa']],
 ['lagrange-guide','Los cinco puntos de Lagrange','Sol–Tierra L1, L2, L3, L4 y L5','Son posiciones de equilibrio del problema restringido de tres cuerpos en un marco que gira con los primarios. L1, L2 y L3 son inestables; los observatorios recorren órbitas de halo o Lissajous y requieren correcciones. L4 y L5 forman triángulos aproximadamente equiláteros. El visor usa posiciones aproximadas y distingue un destino de despliegue de una efeméride medida.',['L1 y L2','A unos 1,5 millones de km de la Tierra'],['Representación','Modelo aproximado']],
];
export function entryFor(item) {
 const category=item.kind==='barycenter'?'solar':item.atlasLayer?(['minor','belts','oort','heliosphere'].includes(item.atlasLayer)?'solar':['clusters','streams','nebulae','dust','bubble'].includes(item.atlasLayer)?'stars':'cosmology'):item.kind==='history'?'history':item.cosmic?(item.kind==='star'?'stars':['galaxy','black-hole'].includes(item.kind)?'galaxies':'cosmology'):item.kind==='history'?'history':item.body?'surface':item.radiusKm?'solar':'deep-space';
 let body=bodyNotes[item.id] || item.summary || `${item.name} forma parte del catálogo público de exploración espacial.`;
 const facts=[];
 if(item.exoSystem)facts.push(['Semieje mayor',item.semimajorAu?`${item.semimajorAu} UA`:'Sin dato'],['Periodo orbital',item.periodDays?`${item.periodDays} días`:'Sin dato'],['Masa',item.massEarth?`${item.massEarth} masas terrestres`:'Sin dato'],['Descubrimiento',item.discoveryMethod||'Estrella anfitriona']);
 if(item.periodSeconds)facts.push(['Periodo de giro',`${item.periodSeconds} s`]);
 if(item.moonTrack)facts.push(['Efemérides JPL',new Date(item.moonTrack.samples[0][0]).toISOString()+' — '+new Date(item.moonTrack.samples.at(-1)[0]).toISOString()],['Fuera del intervalo','Órbita aproximada; los baricentros no se extrapolan']);

 if(item.kind==='black-hole')facts.push(['Masa de referencia',item.massSolar.toLocaleString('es-ES')+' M☉'],['Radio de Schwarzschild (sin rotación)',Math.round(item.radiusKm).toLocaleString('es-ES')+' km'],['Orientación del modelo','Ilustrativa; no medida'],['Observación EHT','2017 · radio a 1,3 mm']);
 if(item.cosmic&&item.radiusKm&&item.kind!=='black-hole')facts.push(['Radio',`${item.radiusKm.toLocaleString('es-ES')} km`]);
 if(!item.cosmic&&item.radiusKm)facts.push(['Radio',`${item.radiusKm.toLocaleString('es-ES')} km`],['Centro orbital',item.parent||'Sistema solar'],['Rotación',item.rotationHours?`${Math.abs(item.rotationHours)} h`:'Síncrona / modelo aproximado']);
 if(item.distanceLy!==undefined)facts.push(['Distancia de referencia',`${item.distanceLy.toLocaleString('es-ES',{maximumFractionDigits:2})} años luz`]);
 if(item.radiusLy)facts.push(['Extensión de referencia',`${(item.radiusLy*2).toLocaleString('es-ES')} años luz`]);
 if(item.motionYears!==undefined)facts.push(['Proyección desde J2000',item.motionYears.toFixed(2)+' años'],['Movimiento','Lineal heliocéntrico; no órbita dinámica']);
 if(item.spect)facts.push(['Tipo espectral',item.spect],['Magnitud aparente',String(item.mag)]);
 if(item.lum)facts.push(['Luminosidad',`${item.lum.toLocaleString('es-ES',{maximumSignificantDigits:4})} L☉`]);
 if(item.lat!==undefined)facts.push(['Latitud',`${item.lat}°`],['Longitud',`${item.lon}°`]);
 if(item.agency)facts.push(['Agencia / operador',item.agency]);
 if(item.designation)facts.push(['Designación',item.designation]);
 if(item.eventDate)facts.push(['Evento de superficie',item.eventDate]);
 if(item.destination)facts.push(['Destino de primera fase',item.destination]);
 if(item.aliases)facts.push(['Identificación adicional',item.aliases]);
 if(item.launchDate)facts.push(['Lanzamiento',item.launchDate.slice(0,10)]);
 if(item.status)facts.push(['Estado / referencia',item.status]);
 if(item.periodHours)facts.push(['Periodo de modelo',`${item.periodHours} horas`]);
 if(item.evidence)facts.push(['Naturaleza de la capa',item.evidence]);
 if(item.redshift!==undefined)facts.push(['Corrimiento al rojo z',String(item.redshift)]);
 if(item.elements)facts.push(['Semieje mayor',`${item.elements.a} UA`],['Excentricidad',String(item.elements.e)],['Inclinación',`${item.elements.i}°`],['Época de elementos',`JD ${item.epoch}`]);
 if(item.source)facts.push(['Fuente',item.source]);
 if(item.catalogNebula){
  facts.push(['Ascensión recta J2000',`${item.raDeg}°`],['Declinación J2000',`${item.decDeg}°`],['Clasificación',item.classification]);
  if(item.radiusArcsec)facts.push(['Radio angular de catálogo',`${item.radiusArcsec}″`]);
  if(item.method)facts.push(['Método de distancia',item.method],['Referencia de distancia',item.author]);
  if(item.errorPc!=null)facts.push(['Error de distancia publicado',`${item.errorPc} pc`]);
  if(item.lowerPc!=null&&item.upperPc!=null)facts.push(['Intervalo de distancia 16–84%',`${item.lowerPc.toFixed(1)}–${item.upperPc.toFixed(1)} pc`]);
  if(item.reliability!=null)facts.push(['Fiabilidad de asociación Gaia',`${(item.reliability*100).toFixed(2)} %`]);
  if(item.noLocation)facts.push(['Ubicación 3D','No disponible: sin distancia aceptada']);
 }
 if(item.positionKm)body+=' La posición corresponde a la época de la instantánea JPL. Se permite una interpolación lineal local de hasta dos días; fuera de ese intervalo se oculta. No es una trayectoria histórica completa.';
 if(item.parent&&item.periodHours)body+=' La trayectoria local es un modelo orbital aproximado, no una solución operacional de navegación.';
 const sourceUrl=item.sourceUrl || (item.positionKm?'https://ssd.jpl.nasa.gov/horizons/':item.radiusKm?'https://science.nasa.gov/solar-system/':item.satrec?'https://celestrak.org/':'https://science.nasa.gov/missions/');
 return {id:item.id,title:item.name,subtitle:item.aliases||item.source||item.agency||category,short:body,body,facts,category,accent:item.color||'#87c9e4',keywords:[String(item.name).toUpperCase()],searchName:item.id,target:item,sourceUrl,noLocation:item.noLocation};
}
export function makeEncyclopedia(extra=[]) {
 const entries=new Map(LIBRARY_ENTRIES.map(e=>[e.id,{...e,sourceUrl:'https://science.nasa.gov/missions/'}]));
 for(const item of [...CELESTIAL_BODIES.map(x=>({...x,kind:x.type})),...(extra.some(x=>x.id?.startsWith('gcat-landing-'))?[]:SURFACE_SITES),...LOCAL_ORBITERS,...FALLBACK_SPACECRAFT,...LAGRANGE_OBJECTS,...COSMIC_OBJECTS,...BLACK_HOLES,...extra])entries.set(item.id,entryFor(item));
 for(const [id,title,subtitle,body,...facts] of methods)entries.set(id,{id,title,subtitle,short:body,body,facts,category:'methods',accent:'#d0b9ff',keywords:[],noLocation:true,sourceUrl:id==='cosmic-strings'?'https://arxiv.org/abs/1303.5085':id==='last-scattering'?'https://irsa.ipac.caltech.edu/data/Planck/release_3/':id==='galaxy-surveys'?'https://heasarc.gsfc.nasa.gov/w3browse/all/twomassrsc.html':id==='cosmic-flows'?'https://projets.ip2i.in2p3.fr/cosmicflows/':id==='cosmic-web'?'https://academic.oup.com/mnras/article/437/4/3442/1005676':id==='hyg-catalog'?'https://github.com/astronexus/HYG-Database':id==='orbital-data'?'https://celestrak.org/':id==='lagrange-guide'?'https://science.nasa.gov/resource/what-is-a-lagrange-point/':'https://science.nasa.gov/universe/overview/'});
 return [...entries.values()];
}
