import * as THREE from 'three';
import {equatorialPosition,PC_KM,LY_KM} from './cosmic-data.js';
import {AU_KM} from './solar-data.js';import {compressedJSON} from './science-data.js';
export function exoplanetOffset(p,date){if(!(p.semimajorAu>0&&p.periodDays>0))return null;const e=Math.min(.99,Math.max(0,p.eccentricity??0)),M=((+date/86400000)%p.periodDays)/p.periodDays*Math.PI*2;let E=M;for(let i=0;i<12;i++)E-=(E-e*Math.sin(E)-M)/(1-e*Math.cos(E));return[p.semimajorAu*AU_KM*(Math.cos(E)-e),0,-p.semimajorAu*AU_KM*Math.sqrt(1-e*e)*Math.sin(E)];}
export function exoplanetCatalog(data){const hosts=new Map(),planets=[];for(const row of data.rows){const r=Object.fromEntries(data.columns.map((k,i)=>[k,row[i]]));if(!(r.sy_dist>0&&Number.isFinite(r.ra)&&Number.isFinite(r.dec)))continue;const id='exo-host-'+r.hostname,position=equatorialPosition(r.ra/15,r.dec,r.sy_dist*PC_KM),common={cosmic:true,distancePc:r.sy_dist,distanceLy:r.sy_dist*PC_KM/LY_KM,source:'NASA Exoplanet Archive',sourceUrl:'https://exoplanetarchive.ipac.caltech.edu/',evidence:'Parámetros publicados · órbita ilustrativa'};
 if(!hosts.has(id))hosts.set(id,{...common,id,name:r.hostname+' · sistema exoplanetario',aliases:r.hostname,exoSystem:id,kind:'star',position,radiusKm:r.st_rad>0?r.st_rad*695700:null,color:'#ffe0b0',viewDistanceKm:AU_KM,summary:'Estrella anfitriona de planetas confirmados. Semiejes, periodos y excentricidades publicados; orientación y fase ilustrativas. No son efemérides.'});
 const p={...common,id:'exo-'+r.pl_name,name:r.pl_name,exoSystem:id,parent:id,kind:'exoplanet',position:[...position],raDeg:r.ra,decDeg:r.dec,semimajorAu:r.pl_orbsmax,periodDays:r.pl_orbper,eccentricity:r.pl_orbeccen,radiusKm:r.pl_rade>0?r.pl_rade*6371:null,massEarth:r.pl_bmasse,discoveryMethod:r.discoverymethod,discoveryYear:r.disc_year,distanceErrorsPc:[r.sy_disterr2,r.sy_disterr1],color:'#a5c9dd',sourceUrl:'https://exoplanetarchive.ipac.caltech.edu/overview/'+encodeURIComponent(r.pl_name),summary:'Exoplaneta confirmado. Superficie lisa sin detalle inventado. Orientación y fase orbitales ilustrativas; excentricidad no medida representada como cero. Los parámetros ausentes no se completan a partir de ajustes incompatibles.'};p.noLocation=!(p.semimajorAu>0&&p.periodDays>0);p.viewDistanceKm=p.radiusKm?p.radiusKm*8:1e6;const off=exoplanetOffset(p,new Date());if(off)p.position=position.map((v,i)=>v+off[i]);planets.push(p);hosts.get(id).viewDistanceKm=Math.max(hosts.get(id).viewDistanceKm,(p.semimajorAu||0)*AU_KM*3);}
 return{hosts:[...hosts.values()],planets};}
export class ExoplanetScene{
 constructor(owner){this.owner=owner;this.hosts=[];this.planets=[];this.group=new THREE.Group();owner.scene.add(this.group);this.nodes=[];}
 async load(){try{Object.assign(this,exoplanetCatalog(await compressedJSON('exoplanets.json.gz')));this.owner.cosmos.targets.push(...this.hosts,...this.planets);window.dispatchEvent(new Event('atlas-change'));}catch(e){console.warn(e);}}
 clear(){this.owner.interactive=this.owner.interactive.filter(x=>!this.group.children.includes(x));for(const n of this.group.children){n.geometry?.dispose();n.material?.dispose();}this.group.clear();this.nodes=[];}
 update(origin){const item=this.owner.focus?.item,host=this.hosts.find(h=>h.id===item?.exoSystem);this.group.visible=!!host&&this.owner.cosmos.layers.stars;if(!host)return;if(this.current!==host.id){this.clear();this.current=host.id;if(host.radiusKm){const m=new THREE.Mesh(new THREE.SphereGeometry(host.radiusKm,32,24),new THREE.MeshBasicMaterial({color:host.color}));m.userData.item=host;this.group.add(m);this.owner.interactive.push(m);}for(const p of this.planets.filter(x=>x.exoSystem===host.id&&!x.noLocation)){const pts=Array.from({length:181},(_,i)=>new THREE.Vector3(...exoplanetOffset(p,i/180*p.periodDays*86400000))),orbit=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:'#74a8cb',transparent:true,opacity:.5}));this.group.add(orbit);let mesh=null;if(p.radiusKm){mesh=new THREE.Mesh(new THREE.SphereGeometry(p.radiusKm,32,20),new THREE.MeshBasicMaterial({color:p.color}));mesh.userData.item=p;this.group.add(mesh);this.owner.interactive.push(mesh);}this.nodes.push({item:p,mesh,orbit});}}
 this.group.position.fromArray(host.position).sub(origin);for(const n of this.nodes){const off=exoplanetOffset(n.item,this.owner.simulationDate);n.item.position=host.position.map((v,i)=>v+off[i]);n.mesh?.position.fromArray(off);n.orbit.visible=this.owner.showPlanetOrbits&&this.owner.orbitIntensity>0;n.orbit.material.opacity=Math.min(1,this.owner.orbitIntensity*(n.item.id===item.id?1.8:1));}}
}
