import {gstime,propagate,eciToEcf,eciToGeodetic} from './satellite-core.js';import {equatorialPosition,LY_KM} from './cosmic-data.js';import {planetPositionAu} from './solar-data.js';
const RAD=Math.PI/180,axes=[equatorialPosition(0,0,1),equatorialPosition(6,0,1),equatorialPosition(0,90,1)];
export function equatorialAngles(p){const [x,y,z]=axes.map(a=>a.reduce((v,n,i)=>v+n*p[i],0));return{raDeg:(Math.atan2(y,x)/RAD+360)%360,decDeg:Math.atan2(z,Math.hypot(x,y))/RAD};}
export function horizontal(raDeg,decDeg,date,lat,lon){const h=gstime(date)+lon*RAD-raDeg*RAD,d=decDeg*RAD,l=lat*RAD,up=Math.sin(l)*Math.sin(d)+Math.cos(l)*Math.cos(d)*Math.cos(h),east=-Math.cos(d)*Math.sin(h),north=Math.cos(l)*Math.sin(d)-Math.sin(l)*Math.cos(d)*Math.cos(h);return{alt:Math.asin(Math.max(-1,Math.min(1,up)))/RAD,az:(Math.atan2(east,north)/RAD+360)%360};}
export function sunCoordinates(date){const p=planetPositionAu('earth',date),e=23.43928*RAD,x=-p.x,y=-p.y*Math.cos(e)+p.z*Math.sin(e),z=-p.y*Math.sin(e)-p.z*Math.cos(e),r=Math.hypot(x,y,z);return{raDeg:(Math.atan2(y,x)/RAD+360)%360,decDeg:Math.asin(z/r)/RAD,vector:[x/r,y/r,z/r]};}
export function satelliteLook(satrec,date,lat,lon){const p=propagate(satrec,date)?.position;if(!p||typeof p==='boolean')return null;const gm=gstime(date),q=eciToEcf(p,gm),l=lat*RAD,L=lon*RAD,n=6378.137/Math.sqrt(1-.00669437999*Math.sin(l)**2),o={x:n*Math.cos(l)*Math.cos(L),y:n*Math.cos(l)*Math.sin(L),z:n*(1-.00669437999)*Math.sin(l)},dx=q.x-o.x,dy=q.y-o.y,dz=q.z-o.z,east=-Math.sin(L)*dx+Math.cos(L)*dy,north=-Math.sin(l)*Math.cos(L)*dx-Math.sin(l)*Math.sin(L)*dy+Math.cos(l)*dz,up=Math.cos(l)*Math.cos(L)*dx+Math.cos(l)*Math.sin(L)*dy+Math.sin(l)*dz,g=eciToGeodetic(p,gm);return{alt:Math.atan2(up,Math.hypot(east,north))/RAD,az:(Math.atan2(east,north)/RAD+360)%360,rangeKm:Math.hypot(dx,dy,dz),lat:g.latitude/RAD,lon:g.longitude/RAD,position:p};}
export function eclipsed(p,s){const dot=p.x*s[0]+p.y*s[1]+p.z*s[2];return dot<0&&p.x*p.x+p.y*p.y+p.z*p.z-dot*dot<6378.137**2;}
export async function satellitePasses(satrec,start,lat,lon){const passes=[],track=[];let active=null;for(let i=0;i<=8640;i++){const date=new Date(+start+i*10000),p=satelliteLook(satrec,date,lat,lon);if(!p)continue;const sun=sunCoordinates(date),shadow=eclipsed(p.position,sun.vector),visible=p.alt>0&&!shadow&&horizontal(sun.raDeg,sun.decDeg,date,lat,lon).alt<-6;if(i%12===0)track.push({time:+date,lat:p.lat,lon:p.lon,shadow});if(p.alt>0){if(!active)active={rise:+date,maxAltitude:p.alt,peak:+date,visible:false,truncatedStart:i===0};if(p.alt>active.maxAltitude){active.maxAltitude=p.alt;active.peak=+date;}active.visible||=visible;}else if(active){active.set=+date;passes.push(active);active=null;}if(i%600===0)await new Promise(r=>setTimeout(r,0));}if(active){active.set=+start+86400000;active.truncated=true;passes.push(active);}return{passes,track};}
export function cosmology(z,H0=67.4,omegaM=.315){if(!Number.isFinite(z)||z<0||z>1100||!Number.isFinite(H0)||H0<=0||!(omegaM>0&&omegaM<.9999))throw Error('Parámetros cosmológicos fuera de rango');const n=4096,a0=1/(1+z),h=(1-a0)/n,omegaR=.000092,lambda=1-omegaM-omegaR;let time=0,comoving=0;for(let i=0;i<=n;i++){const a=a0+i*h,E=Math.sqrt(omegaR/a**4+omegaM/a**3+lambda),w=i===0||i===n?1:i%2?4:2;time+=w/(a*E);comoving+=w/(a*a*E);}const seconds=3.0856775814913673e19/H0;return{lookbackGyr:time*h/3*seconds/31557600/1e9,comovingGly:comoving*h/3*seconds*299792.458/LY_KM/1e9};}
export function searchCatalog(items,{query='',kind='',maxLy=Infinity,ra=null,dec=null,cone=5,origin=[0,0,0],positionFor=x=>Array.isArray(x.position)?x.position:null}={}){const norm=s=>s.toLocaleLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,''),q=norm(query);return items.filter(x=>{if(kind&&x.kind!==kind)return false;if(q&&!norm(`${x.id} ${x.name} ${x.aliases||''}`).includes(q))return false;const p=positionFor(x);if(Number.isFinite(maxLy)&&(!p||Math.hypot(...p.map((v,i)=>v-origin[i]))/LY_KM>maxLy))return false;if(ra!==null&&dec!==null){if(!p&&x.raDeg===undefined)return false;const a=x.raDeg===undefined?equatorialAngles(p):x,cos=Math.sin(dec*RAD)*Math.sin(a.decDeg*RAD)+Math.cos(dec*RAD)*Math.cos(a.decDeg*RAD)*Math.cos((ra-a.raDeg)*RAD);if(Math.acos(Math.min(1,Math.max(-1,cos)))/RAD>cone)return false;}return true;});}
