import * as THREE from 'three';
import {PC_KM,LY_KM,galacticPosition} from './cosmic-data.js';
import {compressedJSON} from './science-data.js';
export function velocityToScene(v){const e=23.43928*Math.PI/180;return[v[0]*PC_KM,(v[2]*Math.cos(e)-v[1]*Math.sin(e))*PC_KM,(-v[1]*Math.cos(e)-v[2]*Math.sin(e))*PC_KM];}
export function projectedStar(base,velocity,years){if(!Number.isFinite(years)||Math.abs(years)>10000)return [...base];return base.map((x,i)=>x+velocity[i]*years);}
export class StellarMotion{
 constructor(cosmos){this.cosmos=cosmos;this.enabled=false;this.solar=false;this.epoch=null;this.rows=null;this.solarVector=galacticPosition(11.1,12.24,7.25);const d=new THREE.Vector3(...this.solarVector).normalize();this.arrow=new THREE.ArrowHelper(d,new THREE.Vector3(),LY_KM,0xffce86);this.arrow.visible=false;cosmos.owner.scene.add(this.arrow);}
 async load(){if(this.rows)return;const d=await compressedJSON('stellar-motion.json.gz');this.rows=new Map(d.rows.map(r=>['hyg-'+r[0],velocityToScene(r.slice(1,4))]));this.epoch=null;}
 update(origin,distance){const c=this.cosmos,s=c.owner;this.arrow.position.copy(origin).negate();this.arrow.visible=this.solar&&c.layers.stars&&distance<100*LY_KM;this.arrow.setLength(5*LY_KM,LY_KM*.35,LY_KM*.15);
 if(!c.starPoints||!this.rows)return;const years=(+s.simulationDate-Date.UTC(2000,0,1,12))/31557600000,valid=Math.abs(years)<=10000,target=this.enabled&&valid?years:0;if(this.epoch!==null&&Math.abs(target-this.epoch)<.01)return;this.epoch=target;
 const attr=c.starPoints.geometry.attributes.position;for(const star of c.stars){star.basePosition??=[...star.position];const v=this.rows.get(star.id);star.position=v?projectedStar(star.basePosition,v,target):[...star.basePosition];star.distanceLy=Math.hypot(...star.position)/LY_KM;if(v){star.motionYears=target;star.velocityKmYear=v;}attr.setXYZ(star.renderIndex,...star.position.map(x=>x/PC_KM));}attr.needsUpdate=true;c.starPoints.geometry.computeBoundingSphere();
 this.status?.(this.enabled?(valid?`Proyección lineal: ${years.toFixed(1)} años desde J2000. Velocidades HYG; no órbitas galácticas.`:'Fuera de ±10.000 años: se muestran posiciones J2000.'): 'Posiciones de referencia J2000');
 }
}
export function mountStellarMotion(scene){const d=document.createElement('dialog');d.className='exploration-dialog';d.innerHTML='<header><strong>Movimientos estelares</strong><button data-close>Cerrar ×</button></header><p>Proyección lineal de las velocidades HYG v4.1, respecto al Sol y ejes J2000. No integra gravedad galáctica ni órbitas de estrellas binarias. Las componentes radiales no medidas pueden estar representadas como cero en el catálogo.</p><label><input data-enabled type="checkbox"> Aplicar el reloj a las estrellas HYG</label><p data-status>Posiciones de referencia J2000</p><div class="exploration-actions"><button data-years="-1000">−1.000 años</button><button data-years="0">J2000</button><button data-years="1000">+1.000 años</button></div><label><input data-solar type="checkbox"> Dirección del movimiento peculiar del Sol</label><p>Flecha de 5 a.l. como ayuda de dirección, no recorrido real. (U,V,W) = (11,1; 12,24; 7,25) km/s respecto al reposo local (LSR); no es su velocidad total alrededor de la galaxia.</p><a href="https://arxiv.org/abs/0912.3693" target="_blank" rel="noreferrer">Schönrich, Binney y Dehnen · referencia solar</a><p>HYG: David Nash · CC BY-SA 4.0. El modelo lineal se limita a ±10.000 años de J2000.</p>';document.body.append(d);const $=q=>d.querySelector(q),m=scene.cosmos.motion;m.status=t=>$('[data-status]').textContent=t;$('[data-close]').onclick=()=>d.close();$('[data-enabled]').onchange=async e=>{try{await m.load();m.enabled=e.target.checked;m.epoch=null;}catch(err){e.target.checked=false;$('[data-status]').textContent='No se pudo cargar el catálogo: '+err.message;}};$('[data-solar]').onchange=e=>m.solar=e.target.checked;d.querySelectorAll('[data-years]').forEach(b=>b.onclick=()=>{const delta=Number(b.dataset.years),date=delta?new Date(+scene.simulationDate):new Date(Date.UTC(2000,0,1,12));if(delta)date.setUTCFullYear(date.getUTCFullYear()+delta);scene.setSimulationDate(date);});return()=>d.showModal();}
