import {solarOrbitGuide} from './solar-orbit-guide.js';
import * as THREE from 'three';
import {PC_KM,LY_KM,galacticPosition,COSMIC_OBJECTS} from './cosmic-data.js';
import {compressedJSON} from './science-data.js';
import {velocityToScene,projectedStar} from './stellar-kinematics.js';
export class StellarMotion{
 constructor(cosmos){this.cosmos=cosmos;this.enabled=false;this.solar=false;this.epoch=null;this.rows=null;this.solarVector=galacticPosition(11.1,12.24,7.25);const d=new THREE.Vector3(...this.solarVector).normalize();this.arrow=new THREE.ArrowHelper(d,new THREE.Vector3(),LY_KM,0xffce86);this.arrow.visible=false;cosmos.owner.scene.add(this.arrow);
 this.guide=solarOrbitGuide();this.galactic=false;this.orbitGuide=new THREE.Line(new THREE.BufferGeometry().setFromPoints(this.guide.points.map(p=>new THREE.Vector3(...p).divideScalar(LY_KM))),new THREE.LineBasicMaterial({color:0xffcc70,transparent:true,opacity:.95,depthTest:false}));this.orbitGuide.scale.setScalar(LY_KM);this.orbitGuide.visible=false;this.orbitGuide.renderOrder=20;cosmos.owner.scene.add(this.orbitGuide);
 this.galacticArrow=new THREE.ArrowHelper(new THREE.Vector3(...this.guide.tangent),new THREE.Vector3(),LY_KM,0xffcc70);this.galacticArrow.visible=false;cosmos.owner.scene.add(this.galacticArrow);
 this.sunPoint=new THREE.Points(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3()]),new THREE.PointsMaterial({color:0xffe8ac,size:9,sizeAttenuation:false,depthTest:false}));this.sunPoint.visible=false;cosmos.owner.scene.add(this.sunPoint);
 this.note=document.createElement('div');this.note.className='solar-motion-note';this.note.hidden=true;this.note.innerHTML='<span></span><button data-galactic>Ver órbita completa</button><button data-hide>Ocultar ×</button>';cosmos.owner.container.append(this.note);this.note.querySelector('[data-galactic]').onclick=()=>this.showGalacticOrbit();this.note.querySelector('[data-hide]').onclick=()=>{this.galactic=false;this.solar=false;this.hideSolarGuide=true;};}
 showGalacticOrbit(){this.galactic=true;this.hideSolarGuide=false;const s=this.cosmos.owner,g=COSMIC_OBJECTS.find(x=>x.id==='milky-way');this.cosmos.layers.galaxies=true;s.focusItem({...g,viewDistanceKm:this.guide.radius*3.2});const normal=new THREE.Vector3(...this.guide.radial).cross(new THREE.Vector3(...this.guide.tangent)).normalize();s.camera.position.copy(normal.multiplyScalar(this.guide.radius*3.2));s.controls.target.set(0,0,0);s.controls.update();s.updateWorld(s.simulationDate,true);}
 async load(){if(this.rows)return;const d=await compressedJSON('stellar-motion.json.gz');this.rows=new Map(d.rows.map(r=>['hyg-'+r[0],velocityToScene(r.slice(1,4))]));this.epoch=null;}
 update(origin,distance){const c=this.cosmos,s=c.owner;this.arrow.position.copy(origin).negate();this.arrow.visible=this.solar&&c.layers.stars&&distance<100*LY_KM;const length=Math.max(1,Math.min(5*LY_KM,distance*.45));this.arrow.setLength(length,length*.18,length*.08);
 const sunFocused=(s.focus.id||s.focus.item?.id)==='sun';if(!sunFocused)this.hideSolarGuide=false;const show=this.galactic||(sunFocused&&!this.hideSolarGuide);this.galacticArrow.position.copy(origin).negate();this.galacticArrow.visible=show&&distance<200000*LY_KM;const gl=Math.max(1,Math.min(5000*LY_KM,distance*.45));this.galacticArrow.setLength(gl,gl*.2,gl*.08);this.orbitGuide.position.copy(origin).negate();this.orbitGuide.visible=this.galactic&&distance>1000*LY_KM&&distance<200000*LY_KM;this.sunPoint.position.copy(origin).negate();this.sunPoint.visible=this.orbitGuide.visible;this.note.hidden=!show;this.note.querySelector('span').textContent=this.orbitGuide.visible?'Sol · órbita galáctica circular aproximada y sentido de giro. No es una trayectoria integrada.':'Sol → sentido de giro alrededor de la galaxia. Flecha de longitud visual.';
 if(!c.starPoints||!this.rows)return;const years=(+s.simulationDate-Date.UTC(2000,0,1,12))/31557600000,valid=Math.abs(years)<=10000,target=this.enabled&&valid?years:0;if(this.epoch!==null&&Math.abs(target-this.epoch)<.01)return;this.epoch=target;
 const attr=c.starPoints.geometry.attributes.position;for(const star of c.stars){star.basePosition??=[...star.position];const v=this.rows.get(star.id);star.position=v?projectedStar(star.basePosition,v,target):[...star.basePosition];star.distanceLy=Math.hypot(...star.position)/LY_KM;if(v){star.motionYears=target;star.velocityKmYear=v;}attr.setXYZ(star.renderIndex,...star.position.map(x=>x/PC_KM));}attr.needsUpdate=true;c.starPoints.geometry.computeBoundingSphere();
 this.status?.(this.enabled?(valid?`Proyección lineal: ${years.toFixed(1)} años desde J2000. Velocidades HYG; no órbitas galácticas.`:'Fuera de ±10.000 años: se muestran posiciones J2000.'): 'Posiciones de referencia J2000');
 }
}
export function mountStellarMotion(scene,pause=()=>scene.setRunning(false)){const d=document.createElement('dialog');d.className='exploration-dialog';d.innerHTML='<header><strong>Movimientos estelares</strong><button data-close>Cerrar ×</button></header><p>Proyección lineal de las velocidades HYG v4.1, respecto al Sol y ejes J2000. No integra gravedad galáctica ni órbitas de estrellas binarias. Las componentes radiales no medidas pueden estar representadas como cero en el catálogo.</p><label><input data-enabled type="checkbox"> Aplicar el reloj a las estrellas HYG</label><p data-status>Posiciones de referencia J2000</p><div class="exploration-actions"><button data-years="-1000">−1.000 años</button><button data-years="0">J2000</button><button data-years="1000">+1.000 años</button></div><button data-galactic-view>Ver órbita del Sol en la Vía Láctea</button><p>Guía circular aproximada y flecha de sentido de giro; no integra la órbita galáctica real del Sol.</p><label><input data-solar type="checkbox"> Dirección del movimiento peculiar del Sol</label><p>Flecha de tamaño adaptado a la vista como ayuda de dirección, no recorrido real. (U,V,W) = (11,1; 12,24; 7,25) km/s respecto al reposo local (LSR); no es su velocidad total alrededor de la galaxia.</p><a href="https://arxiv.org/abs/0912.3693" target="_blank" rel="noreferrer">Schönrich, Binney y Dehnen · referencia solar</a><p>HYG: David Nash · CC BY-SA 4.0. El modelo lineal se limita a ±10.000 años de J2000. Los saltos de mil años pausan el reloj; al reanudarlo vuelve al intervalo orbital 1957–2050.</p>';document.body.append(d);const $=q=>d.querySelector(q),m=scene.cosmos.motion;m.status=t=>$('[data-status]').textContent=t;$('[data-close]').onclick=()=>d.close();$('[data-galactic-view]').onclick=()=>{m.showGalacticOrbit();d.close();};$('[data-enabled]').onchange=async e=>{try{await m.load();m.enabled=e.target.checked;m.epoch=null;}catch(err){e.target.checked=false;$('[data-status]').textContent='No se pudo cargar el catálogo: '+err.message;}};$('[data-solar]').onchange=e=>m.solar=e.target.checked;d.querySelectorAll('[data-years]').forEach(b=>b.onclick=()=>{const delta=Number(b.dataset.years),date=delta?new Date(+scene.simulationDate):new Date(Date.UTC(2000,0,1,12));if(delta)date.setUTCFullYear(date.getUTCFullYear()+delta);pause();scene.setSimulationDate(date);});return()=>d.showModal();}
